### ISSUE TITLE
How to get rid of GoogleMap when we require Apple Map.

### ISSUE THREAD

**Issue by shebinkoshy123** [Fulanko/reactxp-map#10]
react-native-maps: AirGoogleMaps dir must be added to your xCode project to support GoogleMaps on iOS.
![IMG_6694](https://user-images.githubusercontent.com/46756662/65129297-9d9ea180-da18-11e9-8d6b-fbe1b0c47b67.PNG)

**Comment by Fulanko** [comment]
This repo is currently limited to Google maps as it uses react-google-maps for the web implementation. 

If you need cross platform Apple maps, you would need to implement the web part using something like react-mapkit.

If you don't need support for web, you can simply use react-native-maps instead of this repo.
